{{- if (merge (index .Values "pd-replication-timing") .Values.global).workload.serviceAccount.generate }}
{{- include "pinglib.service-account" (list . "pd-replication-timing") -}}
{{- end -}}


{{- define "pd-replication-timing.service-account" -}}
{{- end -}}
